# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/fhir2dataset/query.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.core.common import (
    common_object_pb2 as proto_dot_core_dot_common_dot_common__object__pb2,
)
from syft.proto.lib.python import string_pb2 as proto_dot_lib_dot_python_dot_string__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/lib/fhir2dataset/query.proto',
  package='syft.lib.fhir2dataset',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"proto/lib/fhir2dataset/query.proto\x12\x15syft.lib.fhir2dataset\x1a%proto/core/common/common_object.proto\x1a\x1dproto/lib/python/string.proto\"S\n\tFHIRQuery\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.syft.core.common.UID\x12\x14\n\x0c\x66hir_api_url\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\tb\x06proto3'
  ,
  dependencies=[proto_dot_core_dot_common_dot_common__object__pb2.DESCRIPTOR,proto_dot_lib_dot_python_dot_string__pb2.DESCRIPTOR,])




_FHIRQUERY = _descriptor.Descriptor(
  name='FHIRQuery',
  full_name='syft.lib.fhir2dataset.FHIRQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='syft.lib.fhir2dataset.FHIRQuery.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fhir_api_url', full_name='syft.lib.fhir2dataset.FHIRQuery.fhir_api_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='syft.lib.fhir2dataset.FHIRQuery.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=214,
)

_FHIRQUERY.fields_by_name['id'].message_type = proto_dot_core_dot_common_dot_common__object__pb2._UID
DESCRIPTOR.message_types_by_name['FHIRQuery'] = _FHIRQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FHIRQuery = _reflection.GeneratedProtocolMessageType('FHIRQuery', (_message.Message,), {
  'DESCRIPTOR' : _FHIRQUERY,
  '__module__' : 'proto.lib.fhir2dataset.query_pb2'
  # @@protoc_insertion_point(class_scope:syft.lib.fhir2dataset.FHIRQuery)
  })
_sym_db.RegisterMessage(FHIRQuery)


# @@protoc_insertion_point(module_scope)
