# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/pycolab/backdrop.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.lib.numpy import array_pb2 as proto_dot_lib_dot_numpy_dot_array__pb2
from syft.proto.lib.pycolab import (
    palette_pb2 as proto_dot_lib_dot_pycolab_dot_palette__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/lib/pycolab/backdrop.proto",
    package="syft.lib.pycolab",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n proto/lib/pycolab/backdrop.proto\x12\x10syft.lib.pycolab\x1a\x1bproto/lib/numpy/array.proto\x1a\x1fproto/lib/pycolab/palette.proto"\x85\x01\n\x08\x42\x61\x63kdrop\x12\x30\n\x07\x63urtain\x18\x01 \x01(\x0b\x32\x1a.syft.lib.numpy.NumpyProtoH\x00\x88\x01\x01\x12/\n\x07palette\x18\x02 \x01(\x0b\x32\x19.syft.lib.pycolab.PaletteH\x01\x88\x01\x01\x42\n\n\x08_curtainB\n\n\x08_paletteb\x06proto3',
    dependencies=[
        proto_dot_lib_dot_numpy_dot_array__pb2.DESCRIPTOR,
        proto_dot_lib_dot_pycolab_dot_palette__pb2.DESCRIPTOR,
    ],
)


_BACKDROP = _descriptor.Descriptor(
    name="Backdrop",
    full_name="syft.lib.pycolab.Backdrop",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="curtain",
            full_name="syft.lib.pycolab.Backdrop.curtain",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="palette",
            full_name="syft.lib.pycolab.Backdrop.palette",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_curtain",
            full_name="syft.lib.pycolab.Backdrop._curtain",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="_palette",
            full_name="syft.lib.pycolab.Backdrop._palette",
            index=1,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=117,
    serialized_end=250,
)

_BACKDROP.fields_by_name[
    "curtain"
].message_type = proto_dot_lib_dot_numpy_dot_array__pb2._NUMPYPROTO
_BACKDROP.fields_by_name[
    "palette"
].message_type = proto_dot_lib_dot_pycolab_dot_palette__pb2._PALETTE
_BACKDROP.oneofs_by_name["_curtain"].fields.append(_BACKDROP.fields_by_name["curtain"])
_BACKDROP.fields_by_name["curtain"].containing_oneof = _BACKDROP.oneofs_by_name[
    "_curtain"
]
_BACKDROP.oneofs_by_name["_palette"].fields.append(_BACKDROP.fields_by_name["palette"])
_BACKDROP.fields_by_name["palette"].containing_oneof = _BACKDROP.oneofs_by_name[
    "_palette"
]
DESCRIPTOR.message_types_by_name["Backdrop"] = _BACKDROP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Backdrop = _reflection.GeneratedProtocolMessageType(
    "Backdrop",
    (_message.Message,),
    {
        "DESCRIPTOR": _BACKDROP,
        "__module__": "proto.lib.pycolab.backdrop_pb2"
        # @@protoc_insertion_point(class_scope:syft.lib.pycolab.Backdrop)
    },
)
_sym_db.RegisterMessage(Backdrop)


# @@protoc_insertion_point(module_scope)
