# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/pycolab/enginedirectives.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.lib.python import list_pb2 as proto_dot_lib_dot_python_dot_list__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/lib/pycolab/enginedirectives.proto",
    package="syft.lib.pycolab",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n(proto/lib/pycolab/enginedirectives.proto\x12\x10syft.lib.pycolab\x1a\x1bproto/lib/python/list.proto"\x8f\x01\n\x10\x45ngineDirectives\x12(\n\tz_updates\x18\x01 \x01(\x0b\x32\x15.syft.lib.python.List\x12\x1a\n\rsummed_reward\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\x11\n\tgame_over\x18\x03 \x01(\x08\x12\x10\n\x08\x64iscount\x18\x04 \x01(\x02\x42\x10\n\x0e_summed_rewardb\x06proto3',
    dependencies=[
        proto_dot_lib_dot_python_dot_list__pb2.DESCRIPTOR,
    ],
)


_ENGINEDIRECTIVES = _descriptor.Descriptor(
    name="EngineDirectives",
    full_name="syft.lib.pycolab.EngineDirectives",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="z_updates",
            full_name="syft.lib.pycolab.EngineDirectives.z_updates",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="summed_reward",
            full_name="syft.lib.pycolab.EngineDirectives.summed_reward",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="game_over",
            full_name="syft.lib.pycolab.EngineDirectives.game_over",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="discount",
            full_name="syft.lib.pycolab.EngineDirectives.discount",
            index=3,
            number=4,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_summed_reward",
            full_name="syft.lib.pycolab.EngineDirectives._summed_reward",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=92,
    serialized_end=235,
)

_ENGINEDIRECTIVES.fields_by_name[
    "z_updates"
].message_type = proto_dot_lib_dot_python_dot_list__pb2._LIST
_ENGINEDIRECTIVES.oneofs_by_name["_summed_reward"].fields.append(
    _ENGINEDIRECTIVES.fields_by_name["summed_reward"]
)
_ENGINEDIRECTIVES.fields_by_name[
    "summed_reward"
].containing_oneof = _ENGINEDIRECTIVES.oneofs_by_name["_summed_reward"]
DESCRIPTOR.message_types_by_name["EngineDirectives"] = _ENGINEDIRECTIVES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EngineDirectives = _reflection.GeneratedProtocolMessageType(
    "EngineDirectives",
    (_message.Message,),
    {
        "DESCRIPTOR": _ENGINEDIRECTIVES,
        "__module__": "proto.lib.pycolab.enginedirectives_pb2"
        # @@protoc_insertion_point(class_scope:syft.lib.pycolab.EngineDirectives)
    },
)
_sym_db.RegisterMessage(EngineDirectives)


# @@protoc_insertion_point(module_scope)
