# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/pycolab/palette.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.lib.python import set_pb2 as proto_dot_lib_dot_python_dot_set__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/lib/pycolab/palette.proto",
    package="syft.lib.pycolab",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1fproto/lib/pycolab/palette.proto\x12\x10syft.lib.pycolab\x1a\x1aproto/lib/python/set.proto"9\n\x07Palette\x12.\n\x10legal_characters\x18\x01 \x01(\x0b\x32\x14.syft.lib.python.Setb\x06proto3',
    dependencies=[
        proto_dot_lib_dot_python_dot_set__pb2.DESCRIPTOR,
    ],
)


_PALETTE = _descriptor.Descriptor(
    name="Palette",
    full_name="syft.lib.pycolab.Palette",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="legal_characters",
            full_name="syft.lib.pycolab.Palette.legal_characters",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=81,
    serialized_end=138,
)

_PALETTE.fields_by_name[
    "legal_characters"
].message_type = proto_dot_lib_dot_python_dot_set__pb2._SET
DESCRIPTOR.message_types_by_name["Palette"] = _PALETTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Palette = _reflection.GeneratedProtocolMessageType(
    "Palette",
    (_message.Message,),
    {
        "DESCRIPTOR": _PALETTE,
        "__module__": "proto.lib.pycolab.palette_pb2"
        # @@protoc_insertion_point(class_scope:syft.lib.pycolab.Palette)
    },
)
_sym_db.RegisterMessage(Palette)


# @@protoc_insertion_point(module_scope)
